---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld49
spec:
  replicas: 0
  selector:
    matchLabels:
      app: helloworld49
  template:
    metadata:
      labels:
        app: helloworld49
        owner: hector3
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["/bin/sh", "-c"]
        args: ["echo Hello && sleep 600"]
