---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld121
spec:
  replicas: 0
  selector:
    matchLabels:
      app: helloworld121
  template:
    metadata:
      labels:
        app: helloworld121
        owner: hector2
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["/bin/sh", "-c"]
        args: ["echo Hello && sleep 600"]
