---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld131
spec:
  replicas: 0
  selector:
    matchLabels:
      app: helloworld131
  template:
    metadata:
      labels:
        app: helloworld131
        owner: hector
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["/bin/sh", "-c"]
        args: ["echo Hello && sleep 600"]
