---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld88
spec:
  replicas: 0
  selector:
    matchLabels:
      app: helloworld88
  template:
    metadata:
      labels:
        app: helloworld88
        owner: hector2
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["/bin/sh", "-c"]
        args: ["echo Hello && sleep 600"]
