apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: busybox
        image: busybox
        env:
          - name: TESTENV
            value: "var1"
          - name: TEST2
            value: "var2"
          - name: TEST3
            value: "var3"
        command: ["/bin/sh", "-c"]
        args: ["echo Hello && sleep 600"]
