apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namespace: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: busybox
        image: busybox
        env:
          - name: TESTENV
            value: "${env.name}"
          - name: TEST2
            value: test.${env.hostnamename}
        command: ["/bin/sh", "-c"]
        args: ["echo Hello ${env.name} && sleep 600"]
